tap "cloudfoundry/tap"
tap "drone/drone"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "valelint/vale"
tap "wilmoore/formulae"
brew "openssl@1.1"
brew "icu4c"
brew "autoconf"
brew "bash-completion"
brew "beanstalkd"
brew "brew-php-switcher"
brew "clamav"
brew "cloc"
brew "composer"
brew "git"
brew "gnupg"
brew "go"
brew "graphicsmagick"
brew "imagemagick"
brew "jpegoptim"
brew "jq"
brew "librsvg"
brew "md5sha1sum"
brew "mysql"
brew "node"
brew "optipng"
brew "php", restart_service: true
brew "php-cs-fixer"
brew "php@7.1"
brew "php@7.2", restart_service: true
brew "php@7.3"
brew "postgresql", restart_service: true
brew "rbenv"
brew "ruby"
brew "sloccount"
brew "ssh-copy-id", link: true
brew "subversion"
brew "the_silver_searcher"
brew "tig", args: ["HEAD"]
brew "tree"
brew "watch"
brew "wget"
brew "yarn"
brew "drone/drone/drone"
brew "heroku/brew/heroku"
brew "valelint/vale/vale"
brew "wilmoore/formulae/php-version"
cask "aerial"
cask "font-fira-code"
cask "michaelvillar-timer"
cask "iterm2"
