code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bradlc.vscode-tailwindcss
code --install-extension csstools.postcss
code --install-extension davidanson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension docker.docker
code --install-extension editorconfig.editorconfig
code --install-extension felixfbecker.php-intellisense
code --install-extension getpsalm.psalm-vscode-plugin
code --install-extension github.vscode-github-actions
code --install-extension golang.go
code --install-extension irongeek.vscode-env
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ronnidc.nunjucks
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension shopify.ruby-lsp
code --install-extension whatwedo.twig
code --install-extension xdebug.php-debug
code --install-extension xdebug.php-pack
code --install-extension zobo.php-intellisense